#!/bin/bash

script_dir="$(dirname "$0")"

# shellcheck source=ssh_unlock_config
source "$script_dir/ssh_unlock_config"

if [[ ! -f $KEY_FILE ]] ; then
    echo "Key file missing"
    exit 1
fi

while [ "$DISK_COUNT" -gt 0 ]; 
do 
    ssh "$HOST_ALIAS" cryptroot-unlock < "$KEY_FILE"
    DISK_COUNT=$(("$DISK_COUNT"-1))
done