#!/bin/bash

script_dir="$(dirname "$0")"

# shellcheck source=ssh_unlock_config
source "$script_dir/ssh_unlock_config"

if [[ ! -f $KEY_FILE ]] ; then
    echo "0"
    exit 0
fi


#check if special ssh port is reachable
nc -z "$HOST" "$PORT" -w 5 \
    &> /dev/null \
    || { echo "0"; exit 0;}

#check if pc is booted up
nc -z "$HOST" 22 -w 5 \
    &> /dev/null \
    && { echo "0"; exit 0;}

echo "1"